### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by rremani** [chychen/air_writing#1]
Hi,
First of all thanks for sharing your work.

There are some files missing which are UltraProcess.py and letters.txt.

I found that UltraProcess.py is nothing but the preprocess.py in src folder which creates data.npy and labels.npy but while executing read.py it was giving error that it couldn't locate letters.txt.

Appreciate your thoughts.

**Comment by nsknsl** [comment]
Hi,
Thanks for your attention!
We have updated the repo, please check it.

**Comment by Ghobashii** [comment]
You referenced test_blstm.py but it's missing too?
